"""Module to summarize papers using Claude API."""
import anthropic
from typing import Dict

class PaperSummarizer:
    """Summarizes academic papers using Claude AI."""

    def __init__(self, api_key: str):
        """
        Initialize the summarizer.

        Args:
            api_key: Anthropic API key
        """
        self.client = anthropic.Anthropic(api_key=api_key)

    def summarize_paper(self, paper: Dict) -> str:
        """
        Generate a concise summary of a paper.

        Args:
            paper: Paper dictionary with title, authors, and abstract

        Returns:
            Markdown-formatted summary
        """
        prompt = f"""Please analyze this academic paper and provide a concise summary in markdown format.

Title: {paper['title']}
Authors: {', '.join(paper['authors'][:5])}
Published: {paper['published']}

Abstract:
{paper['summary']}

Please provide:
1. A brief overview (2-3 sentences)
2. Key contributions or findings (3-5 bullet points)
3. Methodology (if applicable, 1-2 sentences)
4. Potential impact or applications

Format the response in clean markdown."""

        try:
            message = self.client.messages.create(
                model="claude-sonnet-4-20250514",
                max_tokens=1024,
                messages=[
                    {"role": "user", "content": prompt}
                ]
            )

            summary = message.content[0].text
            return summary

        except Exception as e:
            print(f"Error summarizing paper '{paper['title']}': {e}")
            return self._create_fallback_summary(paper)

    def _create_fallback_summary(self, paper: Dict) -> str:
        """
        Create a basic summary when API fails.

        Args:
            paper: Paper dictionary

        Returns:
            Basic markdown summary
        """
        authors_str = ", ".join(paper['authors'][:3])
        if len(paper['authors']) > 3:
            authors_str += f" et al."

        return f"""## Overview
This paper titled "{paper['title']}" by {authors_str} was published on {paper['published']}.

## Abstract
{paper['summary'][:500]}{'...' if len(paper['summary']) > 500 else ''}
"""

    def create_markdown_summary(self, paper: Dict, summary: str) -> str:
        """
        Create a complete markdown document for a paper.

        Args:
            paper: Paper dictionary
            summary: Generated summary

        Returns:
            Complete markdown document
        """
        authors_str = ", ".join(paper['authors'][:5])
        if len(paper['authors']) > 5:
            authors_str += f" et al. ({len(paper['authors'])} authors)"

        markdown = f"""# {paper['title']}

**Authors:** {authors_str}
**Published:** {paper['published']}
**Category:** {paper['primary_category']}
**Keywords:** {paper['keyword']}
**PDF:** [{paper['id']}]({paper['pdf_url']})

---

{summary}

---

*Summary generated by Claude AI*
"""

        return markdown
